### PR TITLE
feat: button to go back up

### PR DESCRIPTION
**Pull request by jonas-kgomo**
A button restyling to go up and back to podcasts : 

Screenshot 2022-05-31 at 02 00 11

### CODE REVIEW

**Comment by finmoorhouse** [comment]
I’m not sure about this I’m afraid. Few comments — 

The styling doesn’t quite work for me (in general it looks too scrappy to my eye, sorry)
I had in mind the the arrow should appear once the user has scrolled down even a small amount (so it’s useful wherever you are on the page). As mentioned, see any of the longer pages on longtermism.com <http://longtermism.com/> as an example. I’d be very happy with you copying over what I’ve made there, and just change the colours to black and white.
How about: each episode has the floating back to top arrow (like longtermism.com <http://longtermism.com/>) and also has a ’See more episodes’ button (similar to the bottom of writing pages on my website <https://www.finmoorhouse.com/writing>). I’d prefer this to be the same text style as ‘Your rating’ and ‘Further comments’ with no background.

Thanks anyway for making an effort, and hope that makes sense!

Best,

Fin

**Comment by jonas-kgomo** [comment]
Good morning Fin,

I just noticed the long page, sorry I had not seen that before.
I added the scroll up button and the rest is unchanged!
We now have this, I liked your design better on longtermism website.


[image: Screenshot 2022-05-31 at 11.41.36.png]

Kindest regards,
> Jonas
>

**Comment by finmoorhouse** [comment]
Great, thanks for doing that!

I’m afraid I’m not seeing the screenshot you attached — would you mind resending?

Also would you be able to submit this as a PR to the main repo <https://github.com/finmoorhouse/hearthisidea.com/pulls>? (Sorry if I’m missing something, I’m not super familiar with how PRs work, but the last ones you made worked fine)

Best,

Fin

**Comment by jonas-kgomo** [comment]
Hey Fin,

Yeah, the PR does send the image properly, I don't know why email
doesn't work for this.
Maybe because this is replying to the PR on github, and not just email.

**Comment by finmoorhouse** [comment]
No worries! Just made some weaks of my own and merged. Actually totally missed the message function on GitHub! Let's use that from now on.

**Comment by jonas-kgomo** [comment]
Awesome, that sounds great. So yes, we can comment on the PR , it is much
better.
This looks great now!

**Comment by finmoorhouse** [comment]
Cool! Should be live soon.

**Pull request closed without merging**
